name: PZDragons
version: 1.3
main: com.notjunar.pzdragons.PZDragons
api-version: 1.17
commands:
  pzdragons:
    description: Main command for the PZDragons plugin.
    usage: /pzdragons <version|forcestart|game|ability|reload>
    permission: pzdragons.use
permissions:
  pzdragons.admin:
    description: Allows the user to force-start the game and reload the config.
    default: op
  pzdragons.use:
    description: Allows the user to use the basic commands like checking the version.
    default: true
